python main.py --mode Fed \\
               --approach feddream \\
               --dataset mnist \\
               --device 0 \\
               --inner_loop 10 \\
               --metric l1 \\
               --lr_img 1e-4 \\
               --aug_type color_crop \\
               --mixup_net vanilla \\
               --mixup vanilla \\
               --mix_p 0.5 \\
               --factor 2 \\
               --init mix 